blank_issues_enabled: false
contact_links:
  - name: Question?
    url: https://github.com/lavanyaburlagadda1807/code-server-poc/discussions/new
    about: Ask the community for help on our GitHub Discussions board
  - name: code-server Slack Community
    about: Need immediate help or just want to talk? Hop in our Slack. Note - this Slack is not actively monitored by code-server maintainers.
    url: https://cdr.co/join-community
